server:
  port: ${PORT:${SERVER_PORT:0}}
  
## Microservice info
info:
  app:
    name: api-user
    version: 1.0.0
    description: user microservice
  author: tomyalberdi
  
## Spring 
spring:
  application:
    name: api-user
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coindatabase
    username: usr
    password: pwd
  jpa:
    generate-ddl: true
    hibernate:
      enable_lazy_load_no_trans: true
      event:
        merge:
          entity_copy_observer: allow
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
